### ISSUE TITLE
not keeping changes

### ISSUE THREAD

**Issue by pool2mine** [catherineisonline/bankist#4]
i just want to know if it's me, or the app is not keeping balance and transfer changes after closing or updating browser. i can see changes when hitting the logout button, but if i reload the site it won't keep changes. is this normal behavior?

**Comment by catherineisonline** [comment]
No, it's not meant to save any changes but it sounds like a great addition. This project isn't based on real accounts and everything is hardcoded, or any database for the accounts but of course, it is better to have a more realistic implementation.
